version: "3.7"
services:
  app:
    container_name: book_broker_app
    build:
      context: .
    ports:
      - "8888:8888"
    environment:
      - .env

    depends_on:
      - postgres_db
      - rabbit

  postgres_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mypostgrespassword
    ports:
      - "5435:5432"

  rabbit:
    image: rabbitmq
    ports:
      - "15673:15672"

